### ISSUE TITLE
Return Valid Discounts For User

### ISSUE THREAD

**Issue by matthewjflee** [Vezorla/vezorla-backend#19]
> Finished returning discounts to the front end

In order to return the valid discounts, the user **must** enter in their shipping information

![image](https://user-images.githubusercontent.com/42304224/75636279-6db81480-5bda-11ea-9207-8fed92f85e31.png)

- This returns a boolean if the account was successfully created/saved
- Afterwards, we bring the user to the apply discount page

![image](https://user-images.githubusercontent.com/42304224/75636297-92ac8780-5bda-11ea-9b39-71654a1ec19c.png)

As requested, the return is a JSON object with the code, description, and percent as a decimal

![image](https://user-images.githubusercontent.com/42304224/75636311-ab1ca200-5bda-11ea-8b65-181e40b17b32.png)

Please ensure this works for the front end.

Note, we do not require the email to be sent when grabbing the valid discounts

**Comment by Kwistech** [comment]
There is an inconsistency with the frontend and backend regarding the type and number of input fields. 

Expecting input fields from the frontend:

![image](https://user-images.githubusercontent.com/15060093/76120144-1b963b00-5fae-11ea-9b0b-70017826a3f3.png)

Expecting input fields from the backend:

![Capture2](https://user-images.githubusercontent.com/15060093/76120358-8b0c2a80-5fae-11ea-9f88-461873c35ee1.PNG)

Note that some variable names are inconsistent as well as missing variables from the frontend (info, provice [sic], disabled).

To conclude the issue, I will make the appropriate changes on both the front and backend.
